version: '3.8'

services:
  feature-table-computation:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: feature-table-container
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./transactions.csv:/app/transactions.csv
      - ./users.csv:/app/users.csv
      - ./postgres_dataload.py:/app/postgres_dataload.py
    command: bash -c "sleep 10 && python /app/src/solution_obtained/task1.py && pytest /app/test/test_task1.py"
    networks:
      - app-network
    environment:
      PYTHONUNBUFFERED: "1"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: db
      POSTGRES_DB: test
    depends_on:
      - n26-case-study  # Ensures the PostgreSQL container starts first

  n26-case-study:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
