version: '3.8'

services:
  feature-table-computation:
    build:
      context: .
      dockerfile: Dockerfile-python  # Ensure this matches the actual filename
    container_name: feature-table-container
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    command: bash -c "python /app/src/solution_obtained/task1.py && pytest /app/test/test_task1.py"
    networks:
      - app-network
    environment:
      PYTHONUNBUFFERED: "1"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: db
      POSTGRES_DB: test

  n26-case-study:
    build:
      context: .
      dockerfile: Dockerfile-postgres  # Ensure this matches the actual filename
    container_name: postgres-container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
