FROM postgres:16

# Set the environment variables for Postgres user, password, and database
ENV POSTGRES_USER=test
ENV POSTGRES_PASSWORD=test
ENV POSTGRES_DB=test


# Install Python client and other dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    postgresql-client

# Run the default entrypoint for Postgres
CMD ["postgres"]
